version: '2'

services:  
  # PostgreSQL database
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=liam
      - POSTGRES_PASSWORD=liambao
      - POSTGRES_DB=hypnos
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=liam
      - RABBITMQ_DEFAULT_PASS=liambao
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile_web
    hostname: web
    command: ./run_web.sh
    volumes:
      - .:/src/app  # mount current directory inside container
    ports:
      - "8801:8801"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  #Nginx
  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile_nginx
    ports:
      - "8000:8000"
    volumes:
      - .:/src/app
      # - ~/Desktop/github/Hypnos/nginx/logs:/var/log/nginx
    links:
      - web
    depends_on:
      - web

  # Celery worker
  worker_default:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile_web
    command: ./run_celery.sh
    volumes:
      - .:/src/app
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit

  #Flower
  flower:
    restart: always
    hostname: flower
    build:
      context: .
      dockerfile: docker/Dockerfile_flower
    environment:
      - C_FORCE_ROOT=true
      - AMQP_USERNAME=liam
      - AMQP_PASSWORD=liambao
    ports:
      - "5555:5555"
    volumes:
      - .:/src/app
    links:
      - web
      - worker_default
    depends_on:
      - web
      - worker_default 