FROM nginx

MAINTAINER "Liam Bao<liam_bao@163.com>"

WORKDIR /src/app

ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/hypnos.conf /etc/nginx/sites-available/

RUN mkdir -p /etc/nginx/sites-enabled/\
    && ln -s /etc/nginx/sites-available/hypnos.conf /etc/nginx/sites-enabled/

# RUN mkdir -p /etc/nginx/sites-enabled/\
#     && ln -s /etc/nginx/sites-available/hypnos.conf /etc/nginx/sites-enabled/\
#     && rm /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]