FROM python:3

MAINTAINER "Liam Bao<liam_bao@163.com>"
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /src/app
WORKDIR /src/app
ADD requirements.txt /src/app/
RUN pip install -r requirements.txt
ADD . /src/app/
# create unprivileged user
RUN adduser --disabled-password --gecos '' liam  
RUN chown -R $USER:$USER .